### ISSUE TITLE
Pip installation fails on windows

### ISSUE THREAD

**Issue by kutsurak** [MonetDB/MonetDBLite-Python#38]
Initial report: https://github.com/hannesmuehleisen/MonetDBLite/issues/199#issuecomment-491262100

cc @ssi-bilal

**Comment by kutsurak** [comment]
I will take a look next week. In the meantime could you please 

1. Report here what errors you get when you try to install using pip
2. Try installing directly from the wheel's URL: ~pip install https://files.pythonhosted.org/packages/9b/17/0fdbfda9a1102138a0ea50896c52bf8be8fbf873375e0744eeaf2b909bd9/monetdblite-0.6.3-cp37-cp37m-win_amd64.whl~

**Comment by ssi-bilal** [comment]
> I will take a look next week. In the meantime could you please
> 
> 1. Report here what errors you get when you try to install using pip
> 2. Try installing directly from the wheel's URL: `pip install https://files.pythonhosted.org/packages/9b/17/0fdbfda9a1102138a0ea50896c52bf8be8fbf873375e0744eeaf2b909bd9/monetdblite-0.6.3-cp37-cp37m-win_amd64.whl`

I just ran the given pip install command and it gives following error:
ERROR: monetdblite-0.6.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by kutsurak** [comment]
Hm, I see. Is the windows you are running the 64 or the 32 bit version?

**Comment by ssi-bilal** [comment]
64bit

**Comment by kutsurak** [comment]
OK, I will try to reproduce the issue and I will get back to you. Could you also paste the output of the following commands
`pip --version`
`python --version`
and
`python -c "import struct; print(8*struct.calcsize('P'))`

Thanks!

**Comment by ssi-bilal** [comment]
C:\>pip --version
pip 19.1.1 from c:\users\bilal.ahmed\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)

C:\>python --version
Python 3.7.3

C:\>python -c "import struct; print(8*struct.calcsize('P'))"
32

**Comment by kutsurak** [comment]
The problem was that the Python was a 32-bit installation. `pip install monetdblite` works correctly with 64-bit Python.
