### ISSUE TITLE
how to set embedded_py

### ISSUE THREAD

**Issue by alitrack** [MonetDB/MonetDBLite-Python#45]
* MonetDBLite-Python version:0.6.3
* Python version:3.7.3
* Pip version: 20.0.2
* Operating System:Mac OS 10.15.3

### Description
```
DatabaseError: SQL Query Failed: ParseException:SQLparser:M0M27!Semantic errors TypeException:user.somequery[11]:'pyapi3.eval' library error in: Embedded Python 3 has not been enabled. Start server with --set embedded_py=3
```
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
when I run 

```
CREATE OR REPLACE FUNCTION random_integers(low INTEGER, high INTEGER, amount INTEGER)
RETURNS TABLE(value1 INTEGER, value2 INTEGER)
LANGUAGE PYTHON3 {
 res = dict()
 res['value1'] = numpy.random.randint(low, high, size=(amount,))
 res['value2'] = numpy.random.randint(low, high, size=(amount,))
 return res
};
SELECT * FROM random_integers(0, 10, 1000);
```
got

```
DatabaseError: SQL Query Failed: ParseException:SQLparser:M0M27!Semantic errors TypeException:user.somequery[11]:'pyapi3.eval' library error in: Embedded Python 3 has not been enabled. Start server with --set embedded_py=3
```
how to set embedded_py=3 in embedded monetdb?

**Comment by kutsurak** [comment]
Hi @alitrack 

I am afraid this is not possible in MonetDBLite. This part of the code was written for the MonetDB server and links to libpython, which for various reasons we cannot do in MonetDBLite.

Panos.
