### ISSUE TITLE
Upload source archive to PyPI

### ISSUE THREAD

**Issue by dustalov** [MonetDB/MonetDBLite-Python#46]
Currently, the monetdblite PyPI project contains only pre-built wheels for several versions of Python: https://pypi.org/project/monetdblite/#files. When pip install is called on a platform that is not listed there, the installation fails due to the lack of the uploaded source code.

Although it is possible to install from GitHub, e.g., `pip3 install -e 'git+https://github.com/MonetDB/MonetDBLite-Python@v0.6.3#egg=monetdblite'`, but this makes automatic workflows like CI more complicated.

Could you please upload the source code to PyPI so pip can try building MonetDBLite locally?

**Comment by kutsurak** [comment]
This was a conscious choice because building MonetdbLite-C, the C library that implements the database functionality, is not trivial and we cannot guarantee that `pip install monetdblite` will succeed for every user.

I will prepare and upload to PyPI packages for Python 3.8, but I am reluctant to upload a source package, because this project is in maintenance mode. 

This will happen probably next week.

**Comment by dustalov** [comment]
Thanks, I will be happy to test my code against Python 3.8, too.

When I was building monetdblite from git, everything worked fine both on x86_64 and aarch64, so everything is not *that* non-trivial. I would rather have the opportunity to build it instead of seeing the missing package error, even though I am surely not insisting on that.

Could you please elaborate on the maintenance mode? Somewhere nearby I have read about the plans to use the same codebase as the ‘big’ [MonetDB](https://github.com/monetDB/MonetDB), which is receiving new commits virtually every day. What is your roadmap?

**Comment by kutsurak** [comment]
MonetDBLite-C was a separate codebase forked from MonetDB server that is not being updated anymore. In this sense the project is in maintenance mode. We are actively working on producing an embedded library from the MonetDB server codebase. We will have more to say about this within the next few weeks.

**Comment by kutsurak** [comment]
Hi @dustalov,

I apologize that I didn't manage to build the wheels for Python 3.8 this week. This is the first thing I will do on Monday.

**Comment by kutsurak** [comment]
I just uploaded new binary wheels that include wheels for python 3.8 on Linux and Windows. 

Unfortunately this attempt failed for MacOS, so I will probably have to repeat this exercise tomorrow. 

Let me know if this worked for you.
