### ISSUE TITLE
Precompiled windows wheel

### ISSUE THREAD

**Issue by h5rdly** [MonetDB/MonetDBLite-Python#47]
First of all, this looks like a true gem, an in-process, in-memory, no fuss SQL database that is a bit mightier than SQLite. Cheers!

* MonetDBLite-Python version: latest
* Python version:     3.8.1
* Pip version:            20.1
* Operating System: Windows 10

### Description
Would it be possible to add precompiled binaries for the windows wheel? 

I believe packages like `numpy` were working the user through the same process in the past, but then started coming precompiled.  

This saves both installation time, and errors coming up in different times regarding missing parts of the non-python build toolchain.

### What I Did

ran - 

`pip install monetdblite`

got - 

`Failed building wheel for monetdblite... mingw32-make is not recognized..`

went to - 

[Gohlke's precompiled windows packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/) 

didn't find monetdb :(

**Comment by kutsurak** [comment]
Hi @h5rdly 

The problem you are facing is that there was no binary wheel for MonetDBLite-Python compatible with Python 3.8 on any platform. I just uploaded precompiled wheels for Linux and Windows for python >= 3.5. Take also a look at the discussion at #46. 

Let me know if something did not work out for you.

**Comment by h5rdly** [comment]
Install now, thanks!
